import os
from collections import OrderedDict

CLIENT_ID = os.environ['SPOTIPY_CLIENT_ID']
CLIENT_SECRET = os.environ['SPOTIPY_CLIENT_SECRET']
REDIRECT_URI = os.environ['SPOTIPY_REDIRECT_URI']

CACHES_FOLDER = './.spotify_caches/'

GENRES = OrderedDict({
    'acoustic': 'Acoustic',
    'afrobeat': 'Afrobeat',
    'alt-rock': 'Alt-Rock',
    'alternative': 'Alternative',
    'ambient': 'Ambient',
    'anime': 'Anime',
    'bluegrass': 'Bluegrass',
    'blues': 'Blues',
    'bossanova': 'Bossanova',
    'chill': 'Chill',
    'classical': 'Classical',
    'country': 'Country',
    'dance': 'Dance',
    'disco': 'Disco',
    'edm': 'EDM',
    'electronic': 'Electronic',
    'emo': 'Emo',
    'folk': 'Folk',
    'funk': 'Funk',
    'gospel': 'Gospel',
    'grunge': 'Grunge',
    'happy': 'Happy',
    'hip-hop': 'Hip-Hop',
    'house': 'House',
    'indie': 'Indie',
    'indie-pop': 'Indie-Pop',
    'jazz': 'Jazz',
    'latin': 'Latin',
    'metal': 'Metal',
    'party': 'Party',
    'pop': 'Pop',
    'punk': 'Punk',
    'punk-rock': 'Punk-Rock',
    'reggae': 'Reggae',
    'road-trip': 'Road Trip',
    'rock': 'Rock',
    'rock-n-roll': 'Rock & Roll',
    'romance': 'Romance',
    'r-n-b': 'R&B',
    'sad': 'Sad',
    'sleep': 'Sleep',
    'soul': 'Soul',
    'study': 'Study',
    'summer': 'Summer',
    'work-out': 'Workout',
    'brazil': 'Brazil',
    'british': 'British',
    'cantopop': 'Cantopop',
    'french': 'French',
    'german': 'German',
    'indian': 'Indian',
    'iranian': 'Iranian',
    'j-rock': 'J-rock',
    'k-pop': 'K-pop',
    'latino': 'Latino',
    'mandopop': 'Mandopop',
    'philippines-opm': 'Philippines OPM',
    'spanish': 'Spanish',
    'swedish': 'Swedish',
    'turkish': 'Turkish'
})